CREATE TABLE [dbo].[Data]
(
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Data] NVARCHAR(MAX) NOT NULL,

	[ModifiedBy] UNIQUEIDENTIFIER NOT NULL,
	[ModifiedOn] DATETIME2 (7) NOT NULL,
	[IsArchived] BIT NOT NULL DEFAULT(0),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd]),
	CONSTRAINT [PK_Data] PRIMARY KEY ([Id] ASC)
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[dbo].[DataHistory], DATA_CONSISTENCY_CHECK=ON))
